#!/bin/bash
set -e

root="/etc/treb"

env=$(cat "${root}/env")
export $(echo "${env}" | xargs)

group=$(cat "${root}/group")
source=$(cat "${root}/source")
url=$(eval echo "${source}")

while true
do
	compose=$(curl --fail ${url})
	echo "${compose}" | docker-compose -f - up -d --remove-orphans
	sleep 60
done
