version: 2

jobs:
  validate:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run: ./ci/validate
  deploy:
    docker:
      - image: circleci/python:2.7-jessie
    steps:
      - checkout
      - run: sudo pip install awscli
      - run: aws s3 sync ./deployments s3://jc-deployer/

workflows:
  version: 2
  test_release:
    jobs:
      - validate:
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
      - deploy:
          requires:
            - validate
          filters:
            branches:
              only: master
