version: 2

jobs:
  deploy:
    docker:
      - image: circleci/golang:1.13
    steps:
      - checkout
      - run: docker-compose --version

workflows:
  version: 2
  test_release:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
